(function($){var inviewObjects={},viewportSize,viewportOffset,d=document,w=window,documentElement=d.documentElement,expando=$.expando;$.event.special.inview={add:function(data){inviewObjects[data.guid+"-"+ this[expando]]={data:data,$element:$(this)};},remove:function(data){try{delete inviewObjects[data.guid+"-"+ this[expando]];}catch(e){}}};function getViewportSize(){var mode,domObject,size={height:w.innerHeight,width:w.innerWidth};if(!size.height){mode=d.compatMode;if(mode||!$.support.boxModel){domObject=mode==='CSS1Compat'?documentElement:d.body;size={height:domObject.clientHeight,width:domObject.clientWidth};}}
return size;}
function getViewportOffset(){return{top:w.pageYOffset||documentElement.scrollTop||d.body.scrollTop,left:w.pageXOffset||documentElement.scrollLeft||d.body.scrollLeft};}
function checkInView(){var $elements=$(),elementsLength,i=0;$.each(inviewObjects,function(i,inviewObject){var selector=inviewObject.data.selector,$element=inviewObject.$element;$elements=$elements.add(selector?$element.find(selector):$element);});elementsLength=$elements.length;if(elementsLength){viewportSize=viewportSize||getViewportSize();viewportOffset=viewportOffset||getViewportOffset();for(;i<elementsLength;i++){if(!$.contains(documentElement,$elements[i])){continue;}
var element=$elements[i],$element=$(element),elementSize={},elementOffset={},inView=$element.data('inview'),visiblePartX,visiblePartY,visiblePartsMerged;if($element.css('display')=='none')
{var parentElement=$element.parent();elementOffset.top=parentElement.offset().top;elementOffset.left=parentElement.offset().left;elementSize.height=parentElement.height();elementSize.width=parentElement.width();}else{elementSize={height:$element.height(),width:$element.width()}
elementOffset=$element.offset();}
if(!viewportOffset||!viewportSize){return;}
if(element.offsetWidth>=0&&element.offsetHeight>=0&&element.style.display!="none"&&elementOffset.top+ elementSize.height>viewportOffset.top&&elementOffset.top<viewportOffset.top+ viewportSize.height&&elementOffset.left+ elementSize.width>viewportOffset.left&&elementOffset.left<viewportOffset.left+ viewportSize.width){visiblePartX=(viewportOffset.left>elementOffset.left?'right':(viewportOffset.left+ viewportSize.width)<(elementOffset.left+ elementSize.width)?'left':'both');visiblePartY=(viewportOffset.top>elementOffset.top?'bottom':(viewportOffset.top+ viewportSize.height)<(elementOffset.top+ elementSize.height)?'top':'both');visiblePartsMerged=visiblePartX+"-"+ visiblePartY;if(!inView||inView!==visiblePartsMerged){$element.data('inview',visiblePartsMerged).trigger('inview',[true,visiblePartX,visiblePartY]);}}else if(inView){$element.data('inview',false).trigger('inview',[false]);}}}}
$(w).bind("scroll resize",function(){viewportSize=viewportOffset=null;});if(!documentElement.addEventListener&&documentElement.attachEvent){documentElement.attachEvent("onfocusin",function(){viewportOffset=null;});}
setInterval(checkInView,250);})(jQuery);